services:
  backend:
    restart: on-failure
    build:
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    depends_on:
      - backend_db
    env_file:
      - ./envs/.env_db
      - ./envs/.env_django
    networks:
      - backend_db-network
  backend_db:
    image: postgres:15.1
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./envs/.env_db
    networks:
      - backend_db-network

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis/data
    env_file:
      - ./envs/.env_db
    networks:
      - redis_data-network



volumes:
  postgres:
  redis_data:
    driver: local

networks:
  backend-network:
    driver: bridge
  backend_db-network:
    driver: bridge
  redis_data-network:
    driver: bridge
