# Generated by Django 4.1.5 on 2023-02-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField()),
                ('date_of_add', models.DateTimeField(auto_now_add=True)),
                ('date_of_actualisation', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField()),
                ('date_of_add', models.DateTimeField(auto_now_add=True)),
                ('date_of_actualisation', models.DateField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('preparation_time', models.DurationField()),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('menu_cards', models.ManyToManyField(related_name='%(class)s', to='menucards.menucard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
