# Generated by Django 4.1.5 on 2023-02-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menucards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='date_of_actualisation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='menucard',
            name='date_of_actualisation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
