# Generated by Django 4.1.5 on 2023-02-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menucards', '0002_alter_dish_date_of_actualisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucard',
            name='dishes',
            field=models.ManyToManyField(related_name='%(class)s', to='menucards.dish'),
        ),
    ]
