# Generated by Django 4.1.5 on 2023-02-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menucards', '0003_menucard_dishes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucard',
            name='dishes',
        ),
    ]
