# Generated by Django 4.1.5 on 2023-03-12 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menucards', '0004_remove_menucard_dishes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='menu_cards',
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menucards.dish')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='menu_cards',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='menucards.menucard'),
            preserve_default=False,
        ),
    ]
