# Generated by Django 4.1.5 on 2023-03-12 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menucards', '0005_remove_dish_menu_cards_picture_dish_menu_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='product',
        ),
        migrations.AddField(
            model_name='picture',
            name='dish',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menucards.dish'),
            preserve_default=False,
        ),
    ]
